networks:
  book-reco-network:
    name: ${NETWORK_NAME}

services:
  data-pipeline:
    env_file: ./.env
    environment:
      - REFRESH_DATA=${REFRESH_DATA}
    build: 
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: book-reco-pipeline
    volumes:
      - .:/app
      - ./data:/app/data
    networks:
      - book-reco-network